spring:
#  h2:
#    console:
 #     enabled: true
    datasource:
        url: jdbc:oracle:thin:@localhost:1521:orcl
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: oracle.jdbc.OracleDriver
    jpa:
        hibernate:
            ddl-auto: update

        database-platform: org.hibernate.dialect.OracleDialect
